uwsgi:
  http-socket: :80
  master: true
  processes: 2
  module: spire.drivers.uwsgi
spire:
  components:
    - lattice.server.component.Lattice
  configuration:
    schema:lattice:
      url: sqlite:///lattice.db
